### ISSUE TITLE
Type error when downloading video

### ISSUE THREAD

**Issue by ale-carra** [saschaheim/instantgram#6] opened 2021-05-07 02:16 UTC
When I try to download a video on the feed or a profile with version 7.1.2 the modal never closes and I get the following error:

Uncaught TypeError: e[n] is undefined
(function(){;!function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule:1:9183
    NextJS 13

I am using Firefox 88

**Comment by saschaheim** [comment] 2021-05-07 02:24
Hello thanks for your issue,
Can you post your url so that I can check that?

**Comment by ale-carra** [comment] 2021-05-07 02:42
https://www.instagram.com/p/COjCfAHBgeU/

However the error only occurs when logged in with my user. If I am logged in with another account it doesn't happen

**Comment by saschaheim** [comment] 2021-05-07 02:46
Ok very Strange will Check this soon and Post hopefully a fix for that 👌

**Comment by saschaheim** [comment] 2021-05-08 08:29
Hmm i have tried everything but unfortunately i just can't reproduce your error.
I dont know how to solve your problem.

**Comment by saschaheim** [comment] 2021-05-26 01:52
Have it fixed will be released soon.

**Closed as completed** 2021-05-26 17:41 UTC
Labels: bug, help wanted, good first issue
